### ISSUE TITLE
WebGL build error.

### ISSUE THREAD

**Issue by DmitrijSemyonov** [Mathijs-Bakker/Extenject#82]
**Describe the bug**
Unity does not build a WebGL project while zenject is imported. The Android build works fine.

**To Reproduce**
Import Extenject, run the build for WebGL.

**Expected behavior**
Build completed with a result of 'Completed'.

**Screenshots**
![WebGL build error](https://github.com/Mathijs-Bakker/Extenject/assets/119567063/f82bf2f4-08a9-40c3-8f14-a467ff6e7629)

**Extenject and Unity info (please complete the following information):**
 - Zenject version: 9.2.1, 9.3.1
 - Unity version: 2022.1.1f1.3174
 - Project's scripting backend IL2CPP

**Additional context**
Text errors:

_______________
Building Library\Bee\artifacts\WebGL\ManagedStripped failed with output:
E:\Programs\2022.1.1f1\Editor\Data\il2cpp\build\deploy\UnityLinker.exe --search-directory=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/Bee/PlayerScriptAssemblies --search-directory=E:/Programs/2022.1.1f1/Editor/Data/PlaybackEngines/WebGLSupport/Managed --search-directory=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/PackageCache/com.unity.nuget.newtonsoft-json@3.0.2/Runtime/AOT --search-directory=E:/Programs/unity progect/Drone/Drone/UnityProject/Assets/Plugins/Zenject/Source/Usage --search-directory=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/PackageCache/com.unity.visualscripting@1.7.5/Runtime/VisualScripting.Flow/Dependencies/NCalc --search-directory=E:/Programs/2022.1.1f1/Editor/Data/MonoBleedingEdge/lib/mono/unityaot-linux --search-directory=E:/Programs/2022.1.1f1/Editor/Data/MonoBleedingEdge/lib/mono/unityaot-linux/Facades --out=Library/Bee/artifacts/WebGL/ManagedStripped --include-link-xml=E:/Programs/unity progect/Drone/Drone/UnityProject/Temp/StagingArea/Data/Managed\MethodsToPreserve.xml --include-link-xml=E:/Programs/unity progect/Drone/Drone/UnityProject/Temp/StagingArea/Data/Managed\TypesInScenes.xml --include-link-xml=E:/Programs/unity progect/Drone/Drone/UnityProject/Temp/StagingArea/Data/Managed\SerializedTypes.xml --include-link-xml=E:\Programs\unity progect\Drone\Drone\UnityProject\Assets\Plugins\Zenject\Source\Runtime\link.xml --include-link-xml=E:\Programs\unity progect\Drone\Drone\UnityProject\Assets\Plugins\Zenject\Source\Usage\link.xml --include-directory=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/Bee/PlayerScriptAssemblies --include-directory=E:/Programs/2022.1.1f1/Editor/Data/PlaybackEngines/WebGLSupport/Managed --include-directory=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/PackageCache/com.unity.nuget.newtonsoft-json@3.0.2/Runtime/AOT --include-directory=E:/Programs/unity progect/Drone/Drone/UnityProject/Assets/Plugins/Zenject/Source/Usage --include-directory=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/PackageCache/com.unity.visualscripting@1.7.5/Runtime/VisualScripting.Flow/Dependencies/NCalc --include-directory=E:/Programs/2022.1.1f1/Editor/Data/MonoBleedingEdge/lib/mono/unityaot-linux --include-directory=E:/Programs/2022.1.1f1/Editor/Data/MonoBleedingEdge/lib/mono/unityaot-linux/Facades --dotnetprofile=unityaot-linux --dotnetruntime=Il2Cpp --architecture=EmscriptenJavaScript --platform=WebGL --use-editor-options --enable-engine-module-stripping --engine-modules-asset-file=E:/Programs/2022.1.1f1/Editor/Data/PlaybackEngines/WebGLSupport/modules.asset --editor-data-file=E:/Programs/unity progect/Drone/Drone/UnityProject/Temp/StagingArea/Data/Managed/EditorToUnityLinkerData.json --include-unity-root-assembly=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/Bee/PlayerScriptAssemblies/Assembly-CSharp-firstpass.dll --include-unity-root-assembly=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/Bee/PlayerScriptAssemblies/Assembly-CSharp.dll --include-unity-root-assembly=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/Bee/PlayerScriptAssemblies/Unity.TextMeshPro.dll --include-unity-root-assembly=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/Bee/PlayerScriptAssemblies/UnityEngine.UI.dll --include-unity-root-assembly=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/Bee/PlayerScriptAssemblies/Extenject-Async.dll --include-unity-root-assembly=E:/Programs/unity progect/Drone/Drone/UnityProject/Library/Bee/PlayerScriptAssemblies/Zenject.dll --print-command-line
Fatal error in Unity CIL Linker
Mono.Linker.LinkerFatalErrorException: E:\Programs\unity progect\Drone\Drone\UnityProject\Assets\Plugins\Zenject\Source\Editor\TestFramework\SceneTestFixture.cs(90,13): error IL1005: Zenject.SceneTestFixture.SetUp(): Error processing method 'Zenject.SceneTestFixture.SetUp()' in assembly 'Zenject-TestFramework.dll'
 ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'nunit.framework, Version=3.5.0.0, Culture=neutral, PublicKeyToken=null'
   at Unity.IL2CPP.Common.MissingMethodStubber.GetTypeModule(TypeReference type, IEnumerable`1 assemblies)
   at Unity.Linker.Steps.AddUnresolvedStubsStep.MarkAssemblyOfType(UnityLinkContext context, TypeReference type)
   at Unity.Linker.Steps.Marking.UnresolvedStubMarking.HandleUnresolvedType(TypeReference reference)
   at Unity.Linker.Steps.UnityMarkStep.HandleUnresolvedType(TypeReference reference)
   at Mono.Linker.Steps.MarkStep.MarkCustomAttributes(ICustomAttributeProvider provider, DependencyInfo& reason, IMemberDefinition sourceLocationMember)
   at Mono.Linker.Steps.MarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Unity.Linker.Steps.UnityMarkStep.ProcessMethod(MethodDefinition method, DependencyInfo& reason)
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   --- End of inner exception stack trace ---
   at Mono.Linker.Steps.MarkStep.ProcessQueue()
   at Mono.Linker.Steps.MarkStep.ProcessPrimaryQueue()
   at Mono.Linker.Steps.MarkStep.Process()
   at Mono.Linker.Steps.MarkStep.Process(LinkContext context)
   at Unity.Linker.Steps.UnityMarkStep.Process(LinkContext context)
   at Unity.Linker.UnityPipeline.ProcessStep(LinkContext context, IStep step)
   at Mono.Linker.Pipeline.Process(LinkContext context)
   at Unity.Linker.UnityDriver.UnityRun(Boolean noProfilerAllowed, ILogger customLogger)
   at Unity.Linker.UnityDriver.RunDriverWithoutErrorHandling(ILogger customLogger, Boolean noProfilerAllowed)
   at Unity.Linker.UnityDriver.RunDriver()
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)
_______________

BuildFailedException: Incremental Player build failed!
UnityEditor.Modules.BeeBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at <93a8a0e4d90646a89754560ed9e0635a>:0)
UnityEditor.WebGL.WebGlBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args) (at /Users/bokken/buildslave/unity/build/PlatformDependent/WebGL/Extensions/Unity.WebGL.extensions/BuildPostprocessor.cs:161)
UnityEditor.Modules.DefaultBuildPostprocessor.PostProcess (UnityEditor.Modules.BuildPostProcessArgs args, UnityEditor.BuildProperties& outProperties) (at <93a8a0e4d90646a89754560ed9e0635a>:0)
UnityEditor.PostprocessBuildPlayer.Postprocess (UnityEditor.BuildTargetGroup targetGroup, UnityEditor.BuildTarget target, System.Int32 subtarget, System.String installPath, System.String companyName, System.String productName, System.Int32 width, System.Int32 height, UnityEditor.BuildOptions options, UnityEditor.RuntimeClassRegistry usedClassRegistry, UnityEditor.Build.Reporting.BuildReport report) (at <93a8a0e4d90646a89754560ed9e0635a>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&)
_______________

Build completed with a result of 'Failed' in 17 seconds (17374 ms)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

_______________

UnityEditor.BuildPlayerWindow+BuildMethodException: 3 errors
  at UnityEditor.BuildPlayerWindow+DefaultBuildMethods.BuildPlayer (UnityEditor.BuildPlayerOptions options) [0x002da] in <93a8a0e4d90646a89754560ed9e0635a>:0 
  at UnityEditor.BuildPlayerWindow.CallBuildMethods (System.Boolean askForBuildLocation, UnityEditor.BuildOptions defaultBuildOptions) [0x00080] in <93a8a0e4d90646a89754560ed9e0635a>:0 
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

**Comment by DmitrijSemyonov** [comment]
No this problem with Unity 2022.3.29f1
